Add workflow for updating workflows [WIP]
ckeditor/ckeditor4-workflows-common pull request #1
Opened 2020-10-28 16:31 UTC by f1ames

I decided to add the main/template action as a PR so we can review it and work as normal instead of creating it via GH editor which will be cumbersome.

Also the funny thing is that if this action will be included here it can auto-update itself too I suppose :thinking: So not sure if we should move it as template or leave here eventually.

This is WIP since I need to test how it works.

2020-10-29 10:25 UTC, f1ames commented
Ready for review.

2020-11-05 11:32 UTC, f1ames commented
> The only issue there is that, since it is user (not organization) repo, CKEditor Bot has [Collaborator access level](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository) which means it can't push new workflows - that's why it fails on push step (see e.g. https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository). However, based on logs you can tell it works fine creating/updating workflow files.

Ok, so it turns out that token with `workflows` permission needs to be used for both checkout/pull and push (as mentioned in https://github.com/EndBug/add-and-commit/issues/52#issuecomment-674377928).

2020-11-05 11:32 UTC, f1ames commented
> The only issue there is that, since it is user (not organization) repo, CKEditor Bot has [Collaborator access level](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository) which means it can't push new workflows - that's why it fails on push step (see e.g. https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository). However, based on logs you can tell it works fine creating/updating workflow files.

Ok, so it turns out that token with `workflows` permission needs to be used for both checkout/pull and push (as mentioned in https://github.com/EndBug/add-and-commit/issues/52#issuecomment-674377928).

2020-11-05 13:23 UTC, f1ames commented
@jacekbogdanski I have added dedicated token for pull and push actions and info to README about it - 3541055. It should be the last piece here hopefully :crossed\_fingers:

2020-11-12 08:04 UTC, jacekbogdanski requested changes

2020-11-12 08:04 UTC, jacekbogdanski commented on README.md
> +The `setup-workflows.yml` workflow works in a way that it checkouts this repository once a day in repository it is executed and updates (or creates) all common workflows. Common workflows are stored
```suggestion
The `setup-workflows.yml` workflow checkouts this repository once a day in the repository it is executed and updates (or creates) all common workflows. Common workflows are stored in `./workflows/` directory. There is also `setup-workflows.yml` workflow there, which means, once it is set it will auto-update itself too.
```

2020-11-12 08:04 UTC, jacekbogdanski commented on workflows/setup-workflows.yml
> +            if [[ -e "$file" ]]; then
What is the reason for checking if a file exists if we are iterating over the directory?

2020-11-12 08:04 UTC, jacekbogdanski commented on workflows/setup-workflows.yml
> +              fi
This code path will always result in copying a file even if it exists and did not change. That also means `HAS_CHANGES` will be always set to a truthy value and fail later in `Add changes`. Maybe we could simplify a bit this whole script instead?

```bash
run: |
  rsync -a --include='*/' --include='*.yml' --exclude='*' ./ckeditor4-workflows-common/workflows/ ./github/workflows
  if [[ `git status --porcelain` ]]; then
    echo "HAS_CHANGES=1" >> $GITHUB_ENV
  fi
```

2020-11-12 08:04 UTC, jacekbogdanski commented on workflows/setup-workflows.yml
> +          token: ${{ secrets.TOKEN_WORKFLOWS }}
Maybe `GITHUB_TOKEN_WORKFLOWS`, so it's somehow consistent with `GITHUB_TOKEN` name?

2020-11-12 09:39 UTC, f1ames commented on workflows/setup-workflows.yml
> +          token: ${{ secrets.TOKEN_WORKFLOWS }}
`GITHUB_` prefix is reserved for GitHub internal stuff itself so it cannot be used for user secrets - that's why I have to rename `GITHUB_USERNAME` to `BOT_USERNAME`. But I'm open for any proposals if you have better idea here :+1:

2020-11-12 09:52 UTC, f1ames commented on workflows/setup-workflows.yml
> +              fi
It's much cleaner and simpler in fact :+1: I was only wondering if rsync is a standard lib which will be available on GH Linux image, but it seems it is.

2020-11-12 09:53 UTC, f1ames commented on workflows/setup-workflows.yml
> +            if [[ -e "$file" ]]; then
Solved with switch to rsync - https://github.com/ckeditor/ckeditor4-workflows-common/pull/1#discussion_r521976373.

2020-11-12 13:57 UTC, jacekbogdanski commented on workflows/setup-workflows.yml
> +              fi
We've lost `echo "HAS_CHANGES=1" >> $GITHUB_ENV` here, I will fix it.

2020-11-12 13:59 UTC, jacekbogdanski commented on workflows/setup-workflows.yml
> +          token: ${{ secrets.TOKEN_WORKFLOWS }}
Hah, let's go with `GH_WORKFLOWS_TOKEN` than to distinguish GitHub specific tokens from other environment variables (like CI etc).

2020-11-12 14:04 UTC, jacekbogdanski approved these changes
LGTM!

I've fixed setting `HAS_CHANGES` environment variable and did some env variable renaming.

2020-11-12 14:04 UTC, merged